[project]
name = "vglnt-llamav-ft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "peft>=0.14.0",
    "transformers>=4.47.0",
    "trl>=0.12.2",
]
